ciudad_homepage:
    path:     /hello/{name}
    defaults: { _controller: CiudadBundle:Default:index }

ciudad_cambiar:
    path: /ciudad/cambiar-a-{ciudad}
    defaults: { _controller: CiudadBundle:Default:cambiar }
    requirements:
        ciudad: .+

ciudad_recientes:
    path:    /{ciudad}/recientes.{_format}
    defaults: {_controller: CiudadBundle:Default:Recientes, _format: html }
    requirements:
        _format: html|rss
